app/views/course.py
from flask import (Blueprint, flash, g, redirect, render_template, request, session, url_for, Response, Flask)
import sqlite3
from ..utils import get_course_details, get_user_birth_year, get_user_info, login_required, get_participant_info, get_participant_birth_year
from app.db.db import get_db, close_db


# Création d'un blueprint contenant les routes ayant le préfixe /course/...
course_bp = Blueprint('course_bp', __name__, url_prefix='/course')

# Création d'un URL dynamique pour une page d'information pour chaque course
@course_bp.route('/information/<int:id_course>/<string:course_name>')
def course_information(id_course, course_name):
    # Récupération de la fonction qui récupère toutes les informations sur les courses
    course_details = get_course_details(id_course)
    
    # Envoyer toutes les informations sur une course au template information.html
    if course_details:
        categories = course_details['categories']
        return render_template('course/information.html', id_course=id_course, course_name=course_name,
                               club=course_details['club'],
                               date=course_details['date'],
                               location=course_details['location'],
                               canton=course_details['canton'],
                               country=course_details['country'],
                               site_club=course_details['site_club'],
                               flyers=course_details['flyers'],
                               sport=course_details['sport'],
                               categories=categories)
    else:
        # Affichage d'une erreur dans le cas où les détails d'une course ne sont pas trouvés
        flash("Détails de la course non trouvés", "error")
        return redirect(url_for('home_bp.landing_page'))

# Création d'un URL dynamique pour une page d'information pour chaque course qui sélectionne les catégories auxquelles un utilisateur peut s'inscrire par son âge
@course_bp.route('/information/user/<int:id_course>/<string:course_name>')
@login_required
def course_information_user(id_course, course_name):

    # Récupération de la fonction qui récupère toutes les informations sur les courses
    course_details = get_course_details(id_course)

    # Récupération de l'année de naissance et du sexe de l'utilisateur connecté
    user_id = session.get('user_id')
    user_info = get_user_info(user_id)
    user_sexe = user_info['sexe']
    user_birth_year = int(get_user_birth_year(user_info))

    if course_details:
        categories = course_details['categories']
        
        # Filtrer les catégories en fonction du sexe de l'utilisateur
        filtered_categories = []
        for category in categories:
            age_min = category.get('year_min')
            age_max = category.get('year_max')
            sexe_categorie = category.get('sexe')
            
            if user_sexe == 1:
                if sexe_categorie == "f" or sexe_categorie == "i":
                    if age_min == "-" and age_max == "-":
                        filtered_categories.append(category)
                    elif age_min == "-":
                        if user_birth_year >= int(age_max):
                            filtered_categories.append(category)
                    elif age_max == "-":
                        if user_birth_year <= int(age_min):
                            filtered_categories.append(category)
                    else:
                        if int(age_min) >= user_birth_year >= int(age_max):
                            filtered_categories.append(category)
            elif user_sexe == 2 or user_sexe == 3:
                if sexe_categorie == "h" or sexe_categorie == "i":
                    if age_min == "-" and age_max == "-":
                        filtered_categories.append(category)
                    elif age_min == "-":
                        if user_birth_year >= int(age_max):
                            filtered_categories.append(category)
                    elif age_max == "-":
                        if user_birth_year <= int(age_min):
                            filtered_categories.append(category)
                    else:
                        if int(age_min) >= user_birth_year >= int(age_max):
                            filtered_categories.append(category)

        if not filtered_categories:
            return "Aucune catégorie ne correspond à votre profil"
        else:
            # Retourner les catégories filtrées avec les autres informations de la course
            return render_template('course/user_information.html', id_course=id_course, course_name=course_name,
                                   club=course_details['club'],
                                   date=course_details['date'],
                                   location=course_details['location'],
                                   canton=course_details['canton'],
                                   country=course_details['country'],
                                   site_club=course_details['site_club'],
                                   flyers=course_details['flyers'],
                                   sport=course_details['sport'],
                                   categories=filtered_categories)

    else:
        # Affichage d'une erreur dans le cas où les détails d'une course ne sont pas trouvés
        flash("Détails de la course non trouvés", "error")
        return redirect(url_for('course_bp.course_information'))
    
@course_bp.route('/information/participant/<int:id_course>/<string:course_name>')
def course_competitor(id_course, course_name):
    # Récupération des détails de la course
    course_details = get_course_details(id_course)

    # Connexion à la base de données
    db = get_db()
    cursor = db.cursor()

    # Récupération des informations des utilisateurs inscrits en ligne
    cursor.execute("""
        SELECT categorie.name, users.name, users.surname, users.sexe, users.club
        FROM users 
        JOIN inscription ON users.id = inscription.user_id
        JOIN categorie ON inscription.categorie_id = categorie.id_categorie
        WHERE categorie.course_id = ?
        ORDER BY categorie.name, users.name, users.surname""", (id_course,))
    
    # Récupération des informations des utilisateurs inscrits en ligne
    liste_competitor_users = cursor.fetchall()

    # Récupération des informations des participants inscrits sur place
    cursor.execute("""
        SELECT categorie.name, participant.name, participant.surname, participant.sexe, participant.club
        FROM participant
        JOIN inscription ON participant.id_participant = inscription.participant_id
        JOIN categorie ON inscription.categorie_id = categorie.id_categorie
        WHERE categorie.course_id = ?
        ORDER BY categorie.name, participant.name, participant.surname""", (id_course,))
    
    # Récupération des informations des participants inscrits sur place
    liste_competitor_participants = cursor.fetchall()

    # Fermeture de la connexion à la base de données
    db.close()

    # Combinaison des deux listes d'inscrits
    liste_competitor = liste_competitor_users + liste_competitor_participants

    # Calcul du nombre total de participants
    total_participants = len(liste_competitor)
    
    # Affichage des informations sur une course dans le template liste_competitor.html
    return render_template('course/liste_competitor.html', 
                           id_course=id_course,    
                           course_name=course_name, 
                           liste_competitor=liste_competitor,                         
                           total_participants=total_participants,
                           date=course_details['date'],
                           location=course_details['location'])


# Création d'un URL dynamique pour une page de paiement en ligne pour les utilisateurs
@course_bp.route('/payment/<int:id_course>/<string:course_name>/<string:category_name>', methods=['GET', 'POST'])
@login_required
def user_payment(id_course, course_name, category_name):
    # Récupérer le moyen de paiement sélectionné dans le formulaire
    if request.method == 'POST':
        selected_payment = request.form.get('payment')

        # Récupérer le moyen de paiement sélectionné dans le formulaire
        if selected_payment is None:
            flash("Veuillez choisir un moyen de paiement", "error")
            return redirect(url_for('course_bp.user_payment', id_course=id_course, course_name=course_name, category_name=category_name))

        # Récupérer les détails de la course et de la catégorie en fonction de id_course et category_name
        course_details = get_course_details(id_course)
        
        # Rechercher les informations sur la catégorie choisie
        category_details = None
        for category in course_details['categories']:
            if category['name'] == category_name:
                category_details = category
                break

        if not category_details:
            # Gérer l'erreur si la catégorie n'est pas trouvée
            flash("Catégorie introuvable", "error")
            return redirect(url_for('course_bp.course_information_user', id_course=id_course, course_name=course_name))

        # Rediriger en fonction du moyen de paiement sélectionné
        if selected_payment == 'twint':
            return redirect(url_for('payment_bp.twint_payment_user', id_course=id_course, course_name=course_name, category_name=category_name, category_price=category_details['price']))
        elif selected_payment == 'postfinance':
            return redirect(url_for('payment_bp.postfinance_payment_user', id_course=id_course, course_name=course_name, category_name=category_name, category_price=category_details['price']))
        elif selected_payment == 'paypal':

app/templates/course/information.html
{%extends 'base_user.html' %}

{% block content %}
<body class="background-grey">
    <div class="information-section">
        <div class="course-content">  
            <div class="home-NextCourse">
                <div class="titel-NextCourse">
                    <p class="titel-NextCourse-name">{{ course_name }}</p>
                    <div class="vertical-bar-titel"></div>
                    <div>
                        <p>{{ location }}</p>
                        <p>{{ date }}</p>
                    </div>
                </div>
                <div>
                    {% if g.user  %}
                        <a href="{{ url_for('course_bp.course_information_user', id_course=id_course, course_name=course_name) }}"><button class="btn-inscription">S'inscire</button></a>
                    {% else %}
                        <a href="{{ url_for('auth.login') }}"><button class="btn-inscription">S'inscire</button></a>
                    {% endif %}
                </div>
            </div>
        </div>


        <div class="information-content">
            <div class="information">
                <div class="left-container-information">
                    <h3>Informations</h3>
                    <div class="course-information">
                        <p>Nom : {{ course_name }}</p>
                        <p>Organisateur : {{ club }}</p>
                        <p>Date : {{ date }}</p>
                        {% if canton %}
                            <p>Lieu : {{ location }}, {{ canton }}, {{ country }}</p>
                        {% else %}
                            <p>Lieu : {{ location }}, {{ country }}</p>
                        {% endif %}
                        
                        {% if site_club %}
                            <p>Site officiel : <a href="{{ site_club }}">{{ site_club }}</a></p>
                        {% endif %}
                        <p>Sport : {{ sport }}</p>
                    </div>
                </div>
                <div class="right-container-information">
                    {% if flyers %}
                        <p>{{ flyers }}</p>
                    {% endif %}
                    <a href="{{ url_for('course_bp.course_competitor', id_course=id_course, course_name=course_name, liste_competitor=liste_competitor) }}"><button class="btn-inscription">Liste des inscrits</button></a>
                </div>
            </div>
            <div class="category-content">
                <div class="horizontal-bar"></div>
                <h3>Catégories</h3>
                {% for category in categories %}
                    <div class="category">
                        <div class="category-name">
                            <p>{{ category.name }}</p>
                        </div>
                        <div class="category-information-section">
                            <div class="category-information">
                                <p class="category-information-caracteristic">{{ category.start_time }}</p>
                                <p class="category-information-label">Départ</p>
                            </div>
                            <div class="category-information" id="category-information-year">
                                {% if category["year_min"] == "-" and category["year_max"] != "-":  %}
                                    <p class="category-information-caracteristic">{{ category.year_max }} et plus jeunes</p>
                                {% elif  category["year_max"] == "-" and category["year_min"] != "-": %}
                                    <p class="category-information-caracteristic">{{ category.year_min }} et plus vieux</p>
                                {% elif  category["year_max"] == "-" and category["year_min"] == "-": %} 
                                    <p class="category-information-caracteristic">-</p>
                                {% else %}
                                    <p class="category-information-caracteristic">{{ category.year_min }}-{{ category.year_max }}</p>
                                {% endif %}
                                <p class="category-information-label">Années</p>
                            </div>
                            <div class="category-information">
                                <p class="category-information-caracteristic">{{ category.price }}</p>
                                <p class="category-information-label">Prix</p>
                            </div>
                                                        
                            <div class="vertical-bar-titel"></div>
                            
                            <div class="category-information">
                                <p class="category-information-caracteristic">{{ category.distance }}</p>
                                <p class="category-information-label">Distance</p>
                            </div>
                            {% if category.ascent != "-" %}
                                <div class="category-information">
                                    
                                    <p class="category-information-caracteristic">{{ category.ascent }}</p>
                                    <p class="category-information-label">Montée</p>
                                </div>
                            {% endif %}
                            
                            {% if category.descent != "-" %}
                                <div class="category-information">
                                    <p class="category-information-caracteristic">{{ category.descent }}</p>
                                    <p class="category-information-label">Descente</p>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>

    </div>
</body>

{% endblock %}

app/templates/course/liste_competitor.html
{% extends 'base_user.html' %}

{% block content %}
<body class="background-grey">
    <div class="information-section">
        <div class="course-content">  
            <div class="home-NextCourse">
                <div class="titel-NextCourse">
                    <p class="titel-NextCourse-name">{{ course_name }}</p>
                    <div class="vertical-bar-titel"></div>
                    <div>
                        <p>{{ location }}</p>
                        <p>{{ date }}</p>
                    </div>
                </div>
                <div>
                    {% if g.user %}
                        <a href="{{ url_for('course_bp.course_information_user', id_course=id_course, course_name=course_name) }}"><button class="btn-inscription">S'inscrire</button></a>
                    {% else %}
                        <a href="{{ url_for('auth.login') }}"><button class="btn-inscription">S'inscrire</button></a>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="information-content">
            <div class="information">
                <div class="left-container-information">
                    <h3>Liste des inscrits</h3>
                    {% if liste_competitor %}
                    <table>
                        <thead>
                            <tr>
                                <th>Nom</th>
                                <th>Prénom</th>
                                <th>Sexe</th>
                                <th>Club</th>
                                <th>Catégorie</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for participant in liste_competitor %}
                            <tr>
                                <td>{{ participant[1] }}</td>
                                <td>{{ participant[2] }}</td>
                                <td>
                                    {% if participant[3] == 1 %}
                                        Femme
                                    {% elif participant[3] == 2 %}
                                        Homme
                                    {% elif participant[3] == 3 %}
                                        Autre
                                    {% else %}
                                        Error
                                    {% endif %}
                                </td>
                                <td>{{ participant[4] }}</td>
                                <td>{{ participant[0] }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                        <p>Aucun participant n'est inscrit actuellement.</p>
                    {% endif %}
                    <p>Nombre de participants inscrits : {{ total_participants }}</p>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

app/templates/course/liste_inscription.html
{% extends 'base_admin.html' %}

{% block extra_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/liste_inscription.css') }}">
{% endblock %}

{% block content %}
<body>
    <div class="page-content"> 
        <div class="participation-header">
            <h4>Participation</h4>
            <div class="horizontal-bar"></div>
            <nav class="navigation-content-participation">
                <a href="#liste_competitor">Liste des participants</a>
                <div class="black-point"></div>
                <a href="#total">Décompte total</a>
                <div class="black-point"></div>
                <a href="#category">Décompte par catégorie</a>
            </nav>
            <div class="horizontal-bar"></div>
        </div>

        <div id="liste_section">
                <h3>Listes des participants</h3>
                {% if listes %}
                    <div class="information-participation-table">
                        <table>
                            <thead>
                                <tr>
                                    <th>Catégorie</th>
                                    <th>Année de naissance</th>
                                    <th>Nom</th>
                                    <th>Prénom</th>
                                    <th>Sexe</th>
                                    <th>Localité</th>
                                    <th>Origine</th>
                                    <th>Club</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for participant in listes %}
                                <tr>
                                    <td>{{ participant[7] }}</td>
                                    <td>{{ participant[2] }}</td>
                                    <td>{{ participant[0] }}</td>
                                    <td>{{ participant[1] }}</td>
                                    <td>
                                        {% if participant[3] == 1 %}
                                            Femme
                                        {% elif participant[3] == 2 %}
                                            Homme
                                        {% elif participant[3] == 3 %}
                                            Autre
                                        {% else %}
                                            Error
                                        {% endif %}
                                    </td>
                                    <td>{{ participant[5] }}</td>
                                    <td>{{ participant[4] }}</td>
                                    <td>{{ participant[6] }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <p>Aucun participant n'est inscrit actuellement.</p>
                {% endif %}
        </div>

        <div id="total">
            <h3>Décompte total</h3>
            <div class="information-participation-table">
                <table>
                    <tr>
                        <th style="font-weight: bold; text-align: left;">Nombre de participants inscrits :</th>
                        <td style="font-weight: bold;">{{ total_participants }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: left;">Nombre d'inscriptions en ligne :</th>
                        <td>{{ count_on_site }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: left;">Nombre d'inscriptions sur place :</th>
                        <td>{{ count_online }}</td>
                    </tr>
                    {% if count_guests > 0 %}
                        <tr>
                            <th style="text-align: left;">Nombre d'invités :</th>
                            <td>{{ count_guests }}</td>
                        </tr>
                    {% endif %}
                </table>
            </div>

            <div class="information-participation-table">
                <table>
                    <tr>
                        <th style="text-align: left; font-weight: bold;">Montant total des inscriptions :</th>
                        <td>-</td>
                        <td style="font-weight: bold;">{{ "%.2f" | format(total_amount) }} CHF</td>
                    </tr>
                    <tr>
                        <th style="text-align: left;">Nombre de paiements par carte bancaire :</th>
                        <td>{{ count_carte_bancaire }}</td>
                        <td>{{ "%.2f" | format(payment_counts['total_carte_bancaire']) }} CHF</td>
                    </tr>
                    <tr>
                        <th style="text-align: left;">Nombre de paiements PostFinance :</th>
                        <td>{{ count_post_finance }}</td>
                        <td>{{ "%.2f" | format(payment_counts['total_post_finance']) }} CHF</td>
                    </tr>
                    <tr>
                        <th style="text-align: left;">Nombre de paiements Twint :</th>
                        <td>{{ count_twint }}</td>
                        <td>{{ "%.2f" | format(payment_counts['total_twint']) }} CHF</td>
                    </tr>
                    <tr>
                        <th style="text-align: left;">Nombre de paiements PayPal :</th>
                        <td>{{ count_paypal }}</td>
                        <td>{{ "%.2f" | format(payment_counts['total_paypal']) }} CHF</td>
                    </tr>
                    <tr>
                        <th style="text-align: left;">Nombre de paiements par cash :</th>
                        <td>{{ count_cash }}</td>
                        <td>{{ "%.2f" | format(payment_counts['total_cash']) }} CHF</td>
                    </tr>
                </table>
            </div>
        </div>

        <div id="category">
            <h3>Décompte par catégorie</h3>
            {% for category_name, details in category_counts.items() %}
            <div class="information-participation">
                <div class="category-titel">
                    <div>
                        <p class="category_name">{{ category_name }}</p>
                    </div>
                    <div>
                        <p class="category_price">{{ details['price'] }}</p>
                        <p class="category_price">{{ "%.2f" | format(details['amount']) }} CHF</p>
                    </div>
                </div>

                <ul class="category_payment_place">
                    <li style="font-weight: bold;">Total des participants : {{ details['total'] }}</li>
                    {% if details['invited'] > 0 %}
                        <li>Nombre d'invités : {{ details['invited'] }}</li>
                    {% endif %}
                    <li>Inscrits en ligne : {{ details['online'] }}</li>
                        <div class="category-payment-method-table">
                            <table>
                                <tr>
                                    <th style="text-align: left; font-size: clamp(0.4rem, 2vw, 0.8rem);">Carte bancaire :</th>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ details['carte_bancaire'] }}</td>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ "%.2f" | format(details['amount_carte_bancaire']) }} CHF</td>
                                </tr>
                                <tr>
                                    <th style="text-align: left; font-size: clamp(0.4rem, 2vw, 0.8rem);">PostFinance :</th>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ details['post_finance'] }}</td>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ "%.2f" | format(details['amount_post_finance']) }} CHF</td>
                                </tr>
                                <tr>
                                    <th style="text-align: left; font-size: clamp(0.4rem, 2vw, 0.8rem);">Twint :</th>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ details['twint']['online'] }}</td>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ "%.2f" | format(details['amount_twint']['online']) }} CHF</td>
                                </tr>
                                <tr>
                                    <th style="text-align: left; font-size: clamp(0.4rem, 2vw, 0.8rem);">PayPal :</th>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ details['paypal']['online'] }}</td>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ "%.2f" | format(details['amount_paypal']['online']) }} CHF</td>
                                </tr>
                            </table>
                        </div>
                    <li>Inscrits sur place : {{ details['on_site'] }}</li>
                        <div class="category-payment-method-table">
                            <table>
                                <tr>
                                    <th style="text-align: left; font-size: clamp(0.4rem, 2vw, 0.8rem);">Twint :</th>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ details['twint']['on_site'] }}</td>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ "%.2f" | format(details['amount_twint']['on_site']) }} CHF</td>
                                </tr>
                                <tr>
                                    <th style="text-align: left; font-size: clamp(0.4rem, 2vw, 0.8rem);">PayPal :</th>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ details['paypal']['on_site'] }}</td>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ "%.2f" | format(details['amount_paypal']['on_site']) }} CHF</td>
                                </tr>
                                <tr>
                                    <th style="text-align: left; font-size: clamp(0.4rem, 2vw, 0.8rem);">Cash :</th>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ details['cash'] }}</td>
                                    <td style="font-size: clamp(0.4rem, 2vw, 0.8rem);">{{ "%.2f" | format(details['amount_cash']) }} CHF</td>
                                </tr>
                            </table>
                        </div>
                </ul>
            </div>
        </div>
        {% endfor %}
        </div>

        
    </form>
</body>
{% endblock %}