app/views/payment.py
from flask import (Blueprint, flash, g, redirect, render_template, request, session, url_for, Response, Flask)
import sqlite3
from werkzeug.security import check_password_hash
from app.db.db import get_db
from ..utils import get_course_details, add_user_in_categories, add_participant_in_categories, login_required, login_required_admin

# Création d'un blueprint contenant les routes ayant le préfixe /paiement/...
payment_bp = Blueprint('payment_bp', __name__, url_prefix='/paiement')

# Création d'un URL dynamique pour les utilisateurs qui choississent le moyen de paiement en ligne "twint"
@payment_bp.route('/twint/user/<int:id_course>/<string:course_name>/<string:category_name>/<string:category_price>', methods=['GET'])
@login_required
def twint_payment_user(id_course, course_name, category_name, category_price):
    session['payment_method'] = 'twint'

    # Rediriger vers la page twint_payment.html
    return render_template('payment/twint_payment.html', id_course=id_course, course_name=course_name, category_name=category_name, category_price=category_price)

# Création d'un URL dynamique pour les utilisateurs qui choississent le moyen de paiement en ligne "postfinance"
@payment_bp.route('/postfinance/user/<int:id_course>/<string:course_name>/<string:category_name>/<string:category_price>', methods=['GET'])
@login_required
def postfinance_payment_user(id_course, course_name, category_name, category_price):
    session['payment_method'] = 'postfinance'

    # Rediriger vers la page postfinance_payment.html
    return render_template('payment/postfinance_payment.html', id_course=id_course, course_name=course_name, category_name=category_name, category_price=category_price)

# Création d'un URL dynamique pour les utilisateurs qui choississent le moyen de paiement en ligne "paypal"
@payment_bp.route('/paypal/user/<int:id_course>/<string:course_name>/<string:category_name>/<string:category_price>', methods=['GET'])
@login_required
def paypal_payment_user(id_course, course_name, category_name, category_price):
    session['payment_method'] = 'paypal'

    # Rediriger vers la page paypal_payment.html
    return render_template('payment/paypal_payment.html', id_course=id_course, course_name=course_name, category_name=category_name, category_price=category_price)

# Création d'un URL dynamique pour les utilisateurs qui choississent le moyen de paiement en ligne "carte_bancaire"
@payment_bp.route('/carte_bancaire/user/<int:id_course>/<string:course_name>/<string:category_name>/<string:category_price>', methods=['GET'])
@login_required
def bank_card_payment_user(id_course, course_name, category_name, category_price):
    session['payment_method'] = 'carte bancaire'
    
    # ORediriger vers la page bank_card_payment.html avec les informations nécessaires
    return render_template('payment/bank_card_payment.html', id_course=id_course, course_name=course_name, category_name=category_name, category_price=category_price)

# Création d'un URL dynamique pour inscrire l'utilisateur dans la catégorie choisie après paiement
# Cette route est dédié aux user qui s'inscrire en ligne
@payment_bp.route('/paiement/inscription/confirmation/user/<int:id_course>/<string:course_name>/<string:category_name>', methods=['GET'])
@login_required
def confirmation(id_course, course_name, category_name):
    # Récupération de l'id de l'utilisateur
    user_id = session.get('user_id')
    payment_method = session.get('payment_method')
    
    # Contrôle si l'id de l'utilisateur est toujours disponible
    if user_id is None:
        flash("Erreur: Utilisateur non identifié.")
        return redirect(url_for('course_bp.course_information', id_course=id_course, course_name=course_name))
    
    # Si l'id de l'utilisateur est toujours disponible, on essaye d'inscrire l'utilisateur
    try:
        # Appele de la fonction pour inscrire l'utilisateur dans sa catégorie
        add_user_in_categories(user_id, category_name, payment_method)
        flash("Inscription réussie", "success")
        return render_template('payment/confirmation.html')
    
    # S'il y a un problème, on renvoie l'utilisateur vers la page de paiement
    except Exception as e:
        flash("Une erreur s'est produite lors de l'inscription", "error")
        return redirect(url_for('course_bp.user_payment', id_course=id_course, course_name=course_name, category_name=category_name))

# Création d'un URL dynamique pour les utilisateurs qui choississent le moyen de paiement sur place "twint"
@payment_bp.route('/twint/manual/<int:id_course>/<string:course_name>/<string:category_name>/<string:category_price>', methods=['GET'])
@login_required_admin
def twint_manual_payment(id_course, course_name, category_name, category_price):
    session['payment_method'] = 'twint'

    # Rediriger vers la page payment_manual_payment.html avec les informations nécessaires
    return render_template('payment/twint_manual_payment.html', id_course=id_course, course_name=course_name, category_name=category_name, category_price=category_price)

# Création d'un URL dynamique pour les utilisateurs qui choississent le moyen de paiement sur place "paypal"
@payment_bp.route('/paypal/manual/<int:id_course>/<string:course_name>/<string:category_name>/<string:category_price>', methods=['GET'])
@login_required_admin
def paypal_manual_payment(id_course, course_name, category_name, category_price):
    session['payment_method'] = 'paypal'

    # Rediriger vers la page paypal_manual_payment.html avec les informations nécessaires
    return render_template('payment/paypal_manual_payment.html', id_course=id_course, course_name=course_name, category_name=category_name, category_price=category_price)

# Création d'un URL dynamique pour les utilisateurs qui choississent le moyen de paiement sur place "cash"
@payment_bp.route('/cash/manual/<int:id_course>/<string:course_name>/<string:category_name>/<string:category_price>', methods=['GET'])
@login_required_admin
def cash_manual_payment(id_course, course_name, category_name, category_price):
    session['payment_method'] = 'cash'

    # Rediriger vers la page cash_manual_payment.html avec les informations nécessaires
    return render_template('payment/cash_manual_payment.html', id_course=id_course, course_name=course_name, category_name=category_name, category_price=category_price)

# Création d'un URL dynamique pour les utilisateurs qui sont invités
@payment_bp.route('/cash/manual/<int:id_course>/<string:course_name>/<string:category_name>', methods=['GET'])
@login_required_admin
def invited_payment(id_course, course_name, category_name):
    session['payment_method'] = 'invited'

        # Si des données de formulaire sont envoyées vers la route /admin (ce qui est le cas lorsque le formulaire de login est envoyé)
    if request.method == 'POST':
        # On récupère le champs'password' de la requête HTTP
        password = request.form['password']

        # On récupère l'id de l'administrateur stocké dans la session
        admin_id = session.get('admin_id')

        if admin_id is None:
            flash('ID administrateur manquant dans la session.')
            return render_template('payment/invited_payment.html', id_course=id_course, course_name=course_name, category_name=category_name)
        
        # On récupère la base de données
        db = get_db()

        # On récupère l'administrateur avec l'id_admin spécifié
        admin = db.execute('SELECT * FROM admin WHERE id_admin = ?', (admin_id,)).fetchone()

        error = None
        if not admin or not check_password_hash(admin['mdp'], password):
            error = 'Mot de passe incorrect.'
            flash(error)
            # Rediriger vers la page invited_payment.html avec les informations nécessaires
            return render_template('payment/invited_payment.html', id_course=id_course, course_name=course_name, category_name=category_name)

        # S'il n'y a pas d'erreur, on ajoute l'id de l'administrateur dans une variable de session
        # De cette manière, à chaque requête de l'utilisateur, on pourra récupérer l'id dans le cookie session
        if error is None:
            session.clear()
            session['admin_id'] = admin['id_admin']
            # On redirige l'administrateur vers la page admin_home.html une fois qu'il s'est connecté
            return redirect(url_for('course_bp.manual_confirmation'))
        else:
            # En cas d'erreur, on ajoute l'erreur dans la session et on redirige l'utilisateur vers le formulaire de login
            flash(error)

            # Rediriger vers la page invited_payment.html avec les informations nécessaires
            return render_template('payment/invited_payment.html', id_course=id_course, course_name=course_name, category_name=category_name)
    
    else:
        # Rediriger vers la page invited_payment.html avec les informations nécessaires
        return render_template('payment/invited_payment.html', id_course=id_course, course_name=course_name, category_name=category_name)
    

# Création d'un URL dynamique pour inscrire l'utilisateur dans la catégorie choisie après paiement
# Cette route est dédié aux participants qui s'inscrivent sur place
@payment_bp.route('/paiement/inscription/confirmation/<int:id_course>/<string:course_name>/<string:category_name>', methods=['GET'])
@login_required_admin
def manual_confirmation(id_course, course_name, category_name):
    # Récupération de l'id de l'utilisateur
    participant_id = session.get('participant_id')
    payment_method = session.get('payment_method')
    
    # Contrôle si l'id de l'utilisateur est toujours disponible
    if participant_id is None:
        flash("Erreur: Utilisateur non identifié.")
        return redirect(url_for('course_bp.manual_registration', id_course=id_course, course_name=course_name))

    # Si l'id de l'utilisateur est toujours disponible, on essaye d'inscrire l'utilisateur
    try:

app/templates/payment/bank_card_payment.html
{% extends 'base.html' %}

{% block content %}
<body class="background-grey">
    <div id="payment-section-bank-card">
        <div id="payment-content-left-bank-card">
            <h3>Carte Bancaire</h3>
            <div id="payment-bank-card">
                <div class="entry-box">
                    <input type="text" name="card_name" id="card_name" required>
                    <label for="card_name">Nom sur la carte*</label>
                </div>
                <div class="entry-box">
                    <input type="text" name="card_number" id="card_number" required>
                    <label for="card_number">Numéro sur la carte*</label>
                </div>
                <div class="entry-box">
                    <input type="text" name="valid_date" id="valid_date" placeholder="MM/YY" required>
                    <label for="valid_date">Date de validité*</label>
                </div>
                <div class="entry-box">
                    <input type="text" name="visual_cyptogramme" id="visual_cyptogramme" required>
                    <label for="visual_cyptogramme">Cryptogramme visuel*</label>
                </div>
            </div>
        </div>

        <div id="payment-content-right-bank-card">
            <div class="payment-details">
                <div id="total-content-bank-card">
                    <p class="total">Total</h4>
                    <p class="total-price">{{ category_price }}</p>
                    <a href="{{ url_for('payment_bp.confirmation', id_course=id_course, course_name=course_name, category_name=category_name) }}"><button id="continue-btn-bank-card">Continuer</button></a>
                </div>
                <p class="choixpaiement">Vos informations bancaires ne seront pas enregistrées.</p>
            </div>
        </div>
    </div>
</body>
{% endblock %}

app/templates/payment/cash_manual_payment.html
{% extends 'base.html' %}

{% block content %}
<body class="background-grey">
    <div class="payment-section">
        <h5>Cash</h5>
        <div class="payment-content-cash">
            <div class="payment-cash">
                <div>
                    <h3>Paiement</h3>
                    <p class="price">1x | {{ category_price }}</p>
                </div>
                <div>
                    <div class="total-content-cash">
                        <p class="total">Total</h4>
                        <p class="total-price">{{ category_price }}</p>
                    </div>
                </div>
            </div>
        </div>
        <a href="{{ url_for('payment_bp.manual_confirmation', id_course=id_course, course_name=course_name, category_name=category_name) }}"><button class="btn">Continuer</button></a>
    </div>
</body>
{% endblock %}

app/templates/payment/confirmation.html
{% extends 'base.html' %}

{% block content %}
<body class="background-grey">
    <div class="payment-section">
        <h5>Merci pour votre inscription !</h5>
        <a href="{{ url_for('home_bp.landing_page') }}"><button class="btn" id="btn-confirmation">Retourner à la page d'accueil</button></a>
    </div>
</body>
{% endblock %}

app/templates/payment/invited_payment.html
{% extends 'base.html' %}

{% block content %}
<body class="background-grey">
    <div class="payment-section">
        <h5>Inviter</h5>
        <div class="payment-content-cash">
            <div class="payment-cash">
                <div>
                    <h3>Confirmation</h3>
                    <p>Veuillez entrer votre code d'utilisateur pour confirmer l'invitation.</p>
                </div>
                <div class="input-box">
                    <input type="password" name="password" required>
                    <label for="password">Mot de passe</label>
                </div>
            </div>
        </div>
        <a href="{{ url_for('payment_bp.manual_confirmation', id_course=id_course, course_name=course_name, category_name=category_name) }}"><button class="btn">Continuer</button></a>
    </div>
</body>
{% endblock %}

app/templates/payment/manual_confirmation.html
{% extends 'base.html' %}

{% block content %}
<body class="background-grey">
    <div class="payment-section">
        <h5>Merci pour votre inscription !</h5>
        <a href="{{ url_for('admin.admin_show_home') }}"><button class="btn" id="btn-confirmation">Retourner à la page d'accueil</button></a>
    </div>
</body>
{% endblock %}

app/templates/payment/paypal_manual_payment.html
{% extends 'base.html' %}

{% block content %}
<body class="background-grey">
    <div class="payment-section">
        <h2>PayPal</h2>
        <img class="payment-image-qr-code" src="http://generator.1qr.fr/?id=2rbB0&size=7&date=202005&cache=1" alt="code PayPal">
        <p>QR factice. Ne pas le scaner ?</p>
        <a href="{{ url_for('payment_bp.manual_confirmation', id_course=id_course, course_name=course_name, category_name=category_name) }}"><button class="btn">Continuer</button></a>
    </div>
</body>
{% endblock %}

app/templates/payment/paypal_payment.html
{% extends 'base.html' %}

{% block content %}
<body class="background-grey">
    <div class="payment-section-paypal">
        <img class="paypal-image" src="https://www.1min30.com/wp-content/uploads/2017/09/Paypal-logo-500x417.jpg" alt="PayPal-img">
        <h5>Payer avec PayPal</h5>
        <p>Saississez votre adresse de courriel pour commencer.</p>
        <div class="input-box" id="input-box-paypal">
            <input type="email" name="email" required>
            <label for="email">Adresse de courriel ou numéro de téléphone</label>
            <div id="forgot-email">
                <a href="">Adresse de courriel oublié ?</a>
            </div>
        </div>
        <button class="btn-paypal" id="btn-paypal-1">Suivant</button>
        <div class="horizontal-bar-ou-content">
            <div class="horizontal-bar-ou"></div>
            <p>ou</p>
            <div class="horizontal-bar-ou"></div>
        </div>
        <button class="btn-paypal" id="btn-paypal-2">Payer avec une carte de béit ou de crédit</button>
    </div>
</body>
{% endblock %}

app/templates/payment/postfinance_payment.html
{% extends 'base.html' %}

{% block content %}
<body class="background-grey">
    <div class="payment-section">
        <h2>PostFinance</h2>
        <a href="{{ url_for('payment_bp.confirmation', id_course=id_course, course_name=course_name, category_name=category_name) }}"><button class="btn">Continuer</button></a>
    </div>
</body>
{% endblock %}

app/templates/payment/twint_manual_payment.html
{% extends 'base.html' %}

{% block content %}
<body class="background-grey">
    <div class="payment-section">
        <h5>Twint</h5>
        <img class="payment-image-qr-code" src="https://www.zharity.ch/s/twint_qr-code.svg" alt="code TWINT">
        <p>QR factice. Ne pas le scanner !</p>
        <a href="{{ url_for('payment_bp.manual_confirmation', id_course=id_course, course_name=course_name, category_name=category_name) }}"><button class="btn">Continuer</button></a>
    </div>
</body>
{% endblock %}

app/templates/payment/twint_payment.html
{% extends 'base.html' %}

{% block content %}
<body class="background-grey">
    <div class="payment-section">
        <h5>Twint</h5>
        <img class="payment-image-qr-code" src="https://www.zharity.ch/s/twint_qr-code.svg" alt="code TWINT">
        <p>QR factice. Ne pas le scaner !</p>
        <a href="{{ url_for('payment_bp.confirmation', id_course=id_course, course_name=course_name, category_name=category_name) }}"><button class="btn">Continuer</button></a>
    </div>
</body>
{% endblock %}