app/views/user.py
from flask import (Blueprint, flash, g, redirect, render_template, request, session, url_for)
from app.db.db import get_db
from app.utils import login_required
from ..utils import get_user_info
import os

# Création d'un blueprint contenant les routes ayant le préfixe /admin/...
user_bp = Blueprint('user_bp', __name__, url_prefix='/user')

# Route /admin/home
@user_bp.route('/profil', methods=('GET', 'POST'))
@login_required
def profile_page():
    user_id = session.get('user_id')
    user_info = get_user_info(user_id)
    user_name = user_info['name']
    user_surname = user_info['surname']
    user_sexe = user_info['sexe']


    return render_template('user/profile.html', user_name=user_name, user_surname=user_surname, user_sexe=user_sexe)

# Route /informations-personnelles
@user_bp.route('/informations-personelles', methods=['GET', 'POST'])
def personal_information_page():
    return render_template('user/personal_information.html')

# Route /historique
@user_bp.route('/historique', methods=['GET', 'POST'])
def history_page():
    return render_template('user/history_course.html')

app/templates/user/history_course.html
{% extends 'base_user.html' %}

{% block content %}
<div style="margin-top: 200px;">

</div>
{% endblock %}

app/templates/user/personal_information.html
{% extends 'base_user.html' %}

{% block content %}
<div style="margin-top: 200px;">
</div>
{% endblock %}

app/templates/user/profile.html
{% extends 'base_user.html' %}

{% block content %}
<body>
    <div class="page-content">  
        <h4>Mon profil</h4>
        <h3>Informations personnelles</h3>
        <h5>Nom</h5>
        {{ user_name }}
        <h5>Prénom</h5>
        {{ user_surname }}
        <h3>Mon historique</h3>
        <p>Afficher toutes les courses auxquelles l'utilisateur a participé avec les catégories respective et la date</p>
        
        <h3>Compte et confidentialité</h3>
        <p>Supprimer votre compte</p>
        <p>Cette action va supprimer toutes vos données et ne peut pas être annulée.</p>
        
        <a href="{{ url_for('user_bp.personal_information_page') }}">Mes informations personnelles</a>
        <a href="{{ url_for('user_bp.history_page') }}">Mon historique</a>
    </div>
</body>
{% endblock %}