app/views/auth.py
from flask import (Blueprint, flash, g, redirect, render_template, request, session, url_for)
from werkzeug.security import check_password_hash, generate_password_hash
from app.db.db import get_db
from app.utils import login_required, check_session_expiration
import os

# Création d'un blueprint contenant les routes ayant le préfixe /auth/...
auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

# Route /auth/register
@auth_bp.route('/register', methods=('GET', 'POST'))
def register():
    # Si des données de formulaire sont envoyées vers la route /register (ce qui est le cas lorsque le formulaire d'inscription est envoyé)
    if request.method == 'POST':
        # On récupère les données du formulaire
        name = request.form['name']
        surname = request.form['surname']
        email = request.form['email']
        telephone = request.form['telephone']
        sexe = request.form['sexe']
        age = request.form['age']
        origin = request.form['origin']
        location = request.form['location']
        club = request.form['club']
        license = request.form['license']
        mdp = request.form['mdp']
        mdp_confirm = request.form['mdp_confirm']

        if not name or not surname or not email or not telephone or not sexe or not age or not origin or not location or not mdp or not mdp_confirm:
            error = 'Veuillez remplir tous les champs.'
            flash(error)
            return redirect(url_for('auth.register'))

        # Contrôle que les mots de passe sont identiques
        if mdp != mdp_confirm:
            error = 'Les mots de passe ne correspondent pas.'
            flash(error)
            return redirect(url_for('auth.register'))

        # On récupère la base de données
        db = get_db()

        # Si l'email et le mot de passe ont bien une valeur
        # on essaie d'insérer l'utilisateur dans la base de données
        if email and mdp:
            try:
                db.execute("INSERT INTO users (name, surname, email, telephone, sexe, age, origin, location, club, license, mdp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", (name, surname, email, telephone, sexe, age, origin, location, club, license, generate_password_hash(mdp)))
                # db.commit() permet de valider une modification de la base de données
                db.commit()
            except db.IntegrityError:
                # La fonction flash dans Flask est utilisée pour stocker un message dans la session de l'utilisateur
                # dans le but de l'afficher ultérieurement, généralement sur la page suivante après une redirection
                error = f"L'utilisateur {email} est déjà enregistré."
                flash(error)
                return redirect(url_for("auth.register"))

            return redirect(url_for("auth.login"))
        else:
            error = "Email ou mot de passe invalide"
            flash(error)
            return redirect(url_for("auth.login"))
    else:
        # Si aucune donnée de formulaire n'est envoyée, on affiche le formulaire d'inscription
        return render_template('auth/register.html')

# Route /auth/login
@auth_bp.route('/login', methods=('GET', 'POST'))
def login():
    # Si des données de formulaire sont envoyées vers la route /login (ce qui est le cas lorsque le formulaire de login est envoyé)
    if request.method == 'POST':
        # On récupère les champs 'email' et 'password' de la requête HTTP
        email = request.form['email']  
        password = request.form['password']

        # On récupère la base de données
        db = get_db()

        # On récupère l'utilisateur avec l'email spécifié (une contrainte dans la db indique que le nom d'utilisateur est unique)
        # La virgule après email est utilisée pour créer un tuple contenant une valeur unique
        user = db.execute('SELECT * FROM users WHERE email = ?', (email,)).fetchone()

        # Si aucun utilisateur n'est trouvé ou si le mot de passe est incorrect
        # On crée une variable error
        error = None
        if user is None:
            error = 'Email incorrect.'
            flash(error)
            return redirect(url_for("auth.login"))
        
        if not check_password_hash(user['mdp'], password):
            error = 'Mot de passe incorrect.'
            flash(error)
            return redirect(url_for("auth.login"))
        
        # Si l'utilisateur n'a pas encore défini son mot de passe car il a été inscrit précédemment manuellement
        if not user['mdp']:
            session.clear()
            session['user_id'] = user['id']
            # On redirige vers la page de définition du mot de passe
            return redirect(url_for('auth_bp.set_password'))

        # S'il n'y a pas d'erreur, on ajoute l'id de l'utilisateur dans une variable de session
        # De cette manière, à chaque requête de l'utilisateur, on pourra récupérer l'id dans le cookie session
        if error is None:
            session.clear()
            session['user_id'] = user['id']
            # On redirige l'utilisateur vers la page principale une fois qu'il s'est connecté
            return redirect("/")
        else:
            # En cas d'erreur, on ajoute l'erreur dans la session et on redirige l'utilisateur vers le formulaire de login
            flash(error)
            return redirect(url_for("auth.login"))
    else:
        return render_template('auth/login.html')
    
# Route /auth/logout
@auth_bp.route('/logout')
def logout():
    # Se déconnecter consiste simplement à supprimer le cookie session
    session.clear()

    # On redirige l'utilisateur vers la page principale une fois qu'il s'est déconnecté
    return redirect("/")

# Fonction automatiquement appelée à chaque requête (avant d'entrer dans la route) sur une route appartenant au blueprint 'auth_bp'
# La fonction permet d'ajouter un attribut 'user' représentant l'utilisateur connecté dans l'objet 'g' 
@auth_bp.before_app_request
def load_logged_in_user():

    # On récupère l'id de l'utilisateur stocké dans le cookie session
    user_id = session.get('user_id')

    #On contrôle que la session n'est pas expirée
    check_session_expiration()
    
    # Si l'id de l'utilisateur dans le cookie session est nul, cela signifie que l'utilisateur n'est pas connecté
    # On met donc l'attribut 'user' de l'objet 'g' à None
    if user_id is None:
        g.user = None

    else:
         # On récupère la base de données et on récupère l'utilisateur correspondant à l'id stocké dans le cookie session
        db = get_db()
        g.user = db.execute('SELECT * FROM users WHERE id = ?', (user_id,)).fetchone()

# Route pour gérer les sessions expirées
@auth_bp.route('/session-expired')
def session_expired():
    return render_template('auth/session_expired.html')

# Route /mdp_oublié
@auth_bp.route('/mdp_oublié', methods=['GET', 'POST'])
def forgot_password_page():
    return render_template('auth/forgot_password.html')

app/views/home.py
from flask import (Blueprint, flash, g, redirect, render_template, request, session, url_for, Response, Flask)
import sqlite3
from ..utils import get_all_courses
from email.message import EmailMessage
from app.config import password_email
import smtplib

# Routes /...
home_bp = Blueprint('home', __name__)

# Route /
@home_bp.route('/', methods=('GET', 'POST'))
def landing_page():
    # Récupérez toutes les courses
    all_courses = get_all_courses()
    return render_template('home/index.html', all_courses=all_courses)


# Gestionnaire d'erreur 404 pour toutes les routes inconnues
@home_bp.route('/<path:text>', methods=['GET', 'POST'])
def not_found_error(text):
    return render_template('home/404.html'), 404

# Route /sports
@home_bp.route('/sports', methods=['GET', 'POST'])
def sports_page():
    # Récupérer toutes les courses
    all_courses = get_all_courses()

    # Classer toutes les courses dans des variables en fonction de leur sport
    athletisme = get_all_courses("athlétisme")
    course_a_pied = get_all_courses("course à pied")
    marche = get_all_courses("marche")
    hippisme = get_all_courses("hippisme")
    ski_alpin = get_all_courses("ski alpin")
    ski_nordique = get_all_courses("ski nordique")
    triathlon = get_all_courses("triathlon")
    vtt = get_all_courses("VTT")
    autres = get_all_courses("autres")

    # Envoyer toutes les données au template
    return render_template('home/sports.html', all_courses=all_courses,
                           athletisme=athletisme,
                           course_a_pied=course_a_pied, marche=marche,
                           hippisme=hippisme, ski_alpin=ski_alpin,
                           ski_nordique=ski_nordique, triathlon=triathlon,
                           vtt=vtt, autres=autres)

# Route /contact
@home_bp.route('/contact', methods=['GET', 'POST'])
def contact_page():
    if request.method == 'POST':
        # Récupérer les données du formulaire
        last_name = request.form['last_name']
        first_name = request.form['first_name']
        user_email = request.form['email']
        telephone = request.form['telephone']
        complaint = request.form['complaint']

        sender = "frossardtheo@gmail.com"
        recipient = "frossardtheo@gmail.com"

        # Création du mail le message
        message = f"Nom: {last_name}\nPrénom: {first_name}\nEmail: {user_email}\nTéléphone: {telephone}\nDemande:{complaint}"

        # Créer l'objet EmailMessage
        email_obj = EmailMessage()
        email_obj["From"] = sender
        email_obj["To"] = recipient
        email_obj["Subject"] = "Nouvelle demande depuis le site SportLog"
        email_obj.set_content(message)

        # Établir une connexion sécurisée avec le serveur SMTP
        smtp = smtplib.SMTP_SSL("smtp.gmail.com", port=465)

        smtp.login(sender, password_email)
        smtp.sendmail(sender, recipient, email_obj.as_string())
        smtp.quit()

        # Rediriger vers une page de confirmation
        return redirect(url_for('home.confirmation_page'))

    # Si la méthode est GET, afficher simplement le formulaire
    return render_template('home/contact.html')

# Route pour la page de confirmation
@home_bp.route('/confirmation')
def confirmation_page():
    return render_template('home/confirmation_page.html')

# Route /FAQ
@home_bp.route('/about', methods=['GET', 'POST'])
def about_page():
    return render_template('home/about.html')

app/templates/base.html
<!doctype html>
<head>
    <title>{% block title %}{% endblock %} - Template de base Flask</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block extra_css %}{% endblock %}
</head>

<body>
    
    <section class="content">
        
        
        {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
        {% endfor %}

        {% block content %}{% endblock %}
    </section>

    <script type="text/javascript" src="{{url_for('static', filename='js/script.js')}}"></script>
    {% block extra_js %}{% endblock %}
</body>

app/templates/base_admin.html
<!doctype html>
<head>
    <title>{% block title %}{% endblock %} - Template de base Flask</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block extra_css %}{% endblock %}
</head>

<body>
    <header>
        <a class="logo" href="{{ url_for('admin_bp.admin_show_home') }}">SportLog</a>
        <nav class="navigation">
            <div class="menu-item-content">
                <a class="menu-item" href="{{ url_for('admin_bp.creation') }}">Créer</a>
                <a class="menu-item" href="{{ url_for('admin_bp.courses_historique') }}">Historique</a>
                <a class="menu-item" href="{{ url_for('admin_bp.users') }}">Utilisateurs</a>
            </div>
        </nav>
        <div class="connexion-content">
            <a class="connexion" href="{{ url_for('admin_bp.logout_admin') }}">Se déconnecter</a>
        </div>
    </header>

    
        
        {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
        {% endfor %}

        {% block content %}{% endblock %}
    </section>

    <script type="text/javascript" src="{{url_for('static', filename='js/script.js')}}"></script>
    {% block extra_js %}{% endblock %}
</body>

app/templates/base_login.html
<!doctype html>
<head>
    <title>{% block title %}{% endblock %} - Template de base Flask</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
    
    <section class="content">
        
        
        {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
        {% endfor %}

        {% block content %}{% endblock %}
    </section>

    <script type="text/javascript" src="{{url_for('static', filename='js/script.js')}}"></script>
</body>

app/templates/base_user.html
<!doctype html>
<head>
    <title>{% block title %}{% endblock %} - Template de base Flask</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block extra_css %}{% endblock %}
</head>

<body>
    <header>
        <a class="logo" href="{{ url_for('home.landing_page') }}">SportLog</a>
        <nav class="navigation">
            <div class="menu-item-content">
                <a class="menu-item" href="{{ url_for('home.sports_page') }}">Manifestations</a>
                <a class="menu-item" href="{{ url_for('home.contact_page') }}">Contact</a>
                <a class="menu-item" href="{{ url_for('home.about_page') }}">À propos</a>
            </div>
        </nav>
        <div class="connexion-content">
            {% if g.user  %}
                <a class="connexion" href="{{ url_for('auth.logout') }}">Se déconnecter</a>

            {% else %}
                <a class="connexion" href="{{ url_for('auth.login') }}">Se connecter</a>
            {% endif %}
        </div>
       
    </header>

    
        
        {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
        {% endfor %}

        {% block content %}{% endblock %}
    </section>

    <script type="text/javascript" src="{{url_for('static', filename='js/script.js')}}"></script>
    {% block extra_js %}{% endblock %}
</body>